#############################################################################
# Makefile for building: aip-server
# Generated by qmake (2.01a) (Qt 4.8.6) on: Thu Mar 17 11:57:28 2016
# Project:  aip-server.pro
# Template: app
# Command: /usr/share/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile aip-server.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/share/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		tcpserver.cpp \
		tcpclient.cpp \
		w_home.cpp moc_tcpserver.cpp \
		moc_tcpclient.cpp \
		moc_w_home.cpp \
		qrc_image.cpp
OBJECTS       = main.o \
		tcpserver.o \
		tcpclient.o \
		w_home.o \
		moc_tcpserver.o \
		moc_tcpclient.o \
		moc_w_home.o \
		qrc_image.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		aip-server.pro
QMAKE_TARGET  = aip-server
DESTDIR       = 
TARGET        = aip-server

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_w_home.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: aip-server.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile aip-server.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile aip-server.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/aip-server1.0.0 || $(MKDIR) .tmp/aip-server1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/aip-server1.0.0/ && $(COPY_FILE) --parents my_define.h tcpserver.h tcpclient.h w_home.h .tmp/aip-server1.0.0/ && $(COPY_FILE) --parents image.qrc .tmp/aip-server1.0.0/ && $(COPY_FILE) --parents main.cpp tcpserver.cpp tcpclient.cpp w_home.cpp .tmp/aip-server1.0.0/ && $(COPY_FILE) --parents w_home.ui .tmp/aip-server1.0.0/ && (cd `dirname .tmp/aip-server1.0.0` && $(TAR) aip-server1.0.0.tar aip-server1.0.0 && $(COMPRESS) aip-server1.0.0.tar) && $(MOVE) `dirname .tmp/aip-server1.0.0`/aip-server1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/aip-server1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_tcpserver.cpp moc_tcpclient.cpp moc_w_home.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_tcpserver.cpp moc_tcpclient.cpp moc_w_home.cpp
moc_tcpserver.cpp: tcpclient.h \
		myhelper.h \
		tcpserver.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) tcpserver.h -o moc_tcpserver.cpp

moc_tcpclient.cpp: myhelper.h \
		tcpclient.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) tcpclient.h -o moc_tcpclient.cpp

moc_w_home.cpp: tcpclient.h \
		myhelper.h \
		tcpserver.h \
		w_home.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) w_home.h -o moc_w_home.cpp

compiler_rcc_make_all: qrc_image.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_image.cpp
qrc_image.cpp: image.qrc \
		image/M1S4.jpg \
		image/M1S0.jpg \
		image/M1S1L1.jpg \
		image/None.jpg \
		image/052.png \
		image/107.png \
		image/103.png \
		image/01.bmp \
		image/M1S1.jpg \
		image/M1S1L2.jpg \
		image/053.png \
		image/108.png \
		image/001.png \
		image/104.png \
		image/M1S1L3.jpg \
		image/M1S2.jpg \
		image/054.png \
		image/109.png \
		image/050.png \
		image/105.png \
		image/101.png \
		image/M1S3.jpg \
		image/051.png \
		image/106.png \
		image/M1S0.xcf \
		image/102.png
	/usr/lib/i386-linux-gnu/qt4/bin/rcc -name image image.qrc -o qrc_image.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_w_home.h
compiler_uic_clean:
	-$(DEL_FILE) ui_w_home.h
ui_w_home.h: w_home.ui
	/usr/lib/i386-linux-gnu/qt4/bin/uic w_home.ui -o ui_w_home.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp w_home.h \
		tcpclient.h \
		myhelper.h \
		tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

tcpserver.o: tcpserver.cpp tcpserver.h \
		tcpclient.h \
		myhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpserver.o tcpserver.cpp

tcpclient.o: tcpclient.cpp tcpclient.h \
		myhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpclient.o tcpclient.cpp

w_home.o: w_home.cpp w_home.h \
		tcpclient.h \
		myhelper.h \
		tcpserver.h \
		ui_w_home.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_home.o w_home.cpp

moc_tcpserver.o: moc_tcpserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpserver.o moc_tcpserver.cpp

moc_tcpclient.o: moc_tcpclient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpclient.o moc_tcpclient.cpp

moc_w_home.o: moc_w_home.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_home.o moc_w_home.cpp

qrc_image.o: qrc_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_image.o qrc_image.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

